---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: test-andrea3-scc-storeuser
  labels:
    backstage.io/kubernetes-id: test-andrea3
    app.kubernetes.io/name: test-andrea3
    rht-gitops.com/janus-argocd: test-andrea3
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:test-andrea3:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: test-andrea3-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: test-andrea3
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:test-andrea3:storeuseradmin-sa
